### ISSUE TITLE
Does it still work on gnome 3.28?

### ISSUE THREAD

**Issue by MaikKlein** [csxr/i3-gnome#31]
I am currently on 18.04 with gnome 3.28

```
exec --no-startup-id gome-flashback
exec_always --no-startup-id gnome-power-manager
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
```
Atm what doesn't work for me:

* Display inside the control center, nor are any settings applied
* No input settings are applied
* Mediakeys are not working

Do I have to update to 3.32?

**Comment by csxr** [comment]
Yes, you have to update to GNOME 3.32.x because there are specific changes regarding
`gnome-settings-daemon` and a lot of changes related.

Here, you can get more information about:
- https://github.com/GNOME/gnome-settings-daemon/blob/master/NEWS
- https://bugs.archlinux.org/task/53800
- https://github.com/51v4n/i3-gnome/issues/9
